---
- name: "[InfluxDB] Create users"
  influxdb_user_custom:
    hostname: "{{ influxdb_management_hostname | default(omit, true) }}"
    port: "{{ influxdb_management_port | default(omit, true) }}"
    validate_certs: "{{ influxdb_management_validate_certs | default(omit, true) }}"
    proxies: "{{ influxdb_management_proxies | default(omit, true) }}"
    login_password: "{{ influxdb_management_login_password | default(omit, true) }}"
    login_username: "{{ influxdb_management_login_username | default(omit, true) }}"
    state: present
    retries: "{{ influxdb_management_retries | default(omit, true) }}"
    ssl: "{{ influxdb_management_ssl | default(omit, true) }}"
    timeout: "{{ influxdb_management_timeout | default(omit, true) }}"
    udp_port: "{{ influxdb_management_udp_port | default(omit, true) }}"
    use_udp: "{{ influxdb_management_use_udp | default(omit, true) }}"
    user_name: "{{ item.user_name | default(omit) }}"
    user_password: "{{ item.user_password | default(omit) }}"
    admin: "{{ item.admin | default(omit) }}"
    grants: "{{ item.grants | default(omit) }}"
  no_log: "{{ influxdb_hide_log }}"
  with_items:
    - "{{ influxdb_users_to_create }}"

- name: "[InfluxDB] Delete unwanted users"
  influxdb_user_custom:
    hostname: "{{ influxdb_management_hostname | default(omit, true) }}"
    port: "{{ influxdb_management_port | default(omit, true) }}"
    validate_certs: "{{ influxdb_management_validate_certs | default(omit, true) }}"
    proxies: "{{ influxdb_management_proxies | default(omit, true) }}"
    login_password: "{{ influxdb_management_login_password | default(omit, true) }}"
    login_username: "{{ influxdb_management_login_username | default(omit, true) }}"
    state: absent
    retries: "{{ influxdb_management_retries | default(omit, true) }}"
    ssl: "{{ influxdb_management_ssl | default(omit, true) }}"
    timeout: "{{ influxdb_management_timeout | default(omit, true) }}"
    udp_port: "{{ influxdb_management_udp_port | default(omit, true) }}"
    use_udp: "{{ influxdb_management_use_udp | default(omit, true) }}"
    user_name: "{{ item }}"
  no_log: "{{ influxdb_hide_log }}"
  with_items:
    - "{{ influxdb_users_to_delete }}"
