---
- name: "[InfluxDB] Copy custom logrotate config if exists"
  template:
    src: "{{ influxdb_custom_logrotate_tpl }}"
    dest: "/etc/logrotate.d/influxdb"
    force: true
    backup: true
    mode: 0644
    owner: root
    validate: logrotate --force %s
  when:
    - influxdb_custom_logrotate | d("") | trim | length > 0
    - influxdb_custom_logrotate != None
