---
- name: "[InfluxDB] Create retention policies"
  influxdb_retention_policy:
    hostname: "{{ influxdb_management_hostname | default(omit, true) }}"
    port: "{{ influxdb_management_port | default(omit, true) }}"
    validate_certs: "{{ influxdb_management_validate_certs | default(omit, true) }}"
    proxies: "{{ influxdb_management_proxies | default(omit, true) }}"
    login_password: "{{ influxdb_management_login_password | default(omit, true) }}"
    login_username: "{{ influxdb_management_login_username | default(omit, true) }}"
    retries: "{{ influxdb_management_retries | default(omit, true) }}"
    ssl: "{{ influxdb_management_ssl | default(omit, true) }}"
    timeout: "{{ influxdb_management_timeout | default(omit, true) }}"
    udp_port: "{{ influxdb_management_udp_port | default(omit, true) }}"
    use_udp: "{{ influxdb_management_use_udp | default(omit, true) }}"
    policy_name: "{{ item.policy_name | default(omit, true) }}"
    database_name: "{{ item.database_name | default(omit, true) }}"
    default: "{{ item.default | default(omit, true) }}"
    duration: "{{ item.duration | default(omit, true) }}"
    replication: "{{ item.replication | default(omit, true) }}"
  no_log: "{{ influxdb_hide_log }}"
  with_items:
    - "{{ influxdb_retention_policies_to_create }}"
